# Makefile by Carlos Zatarain
# 7/27/2022

.SILENT: all
.SILENT: keygen
.SILENT: Win_keygen

all:
	./CrackOrKeyme1.exe

keygen:
	g++ LCK1_Keygen.cpp -o LCK1Keygen.exe
	./LCK1Keygen.exe
	rm LCK1Keygen.exe

Win_keygen:
	g++ LCK1_Keygen.cpp -o LCK1Keygen.exe
	./LCK1Keygen.exe
	del LCK1Keygen.exe
